### ISSUE TITLE
Browser tests in sub-directories fail to run

### ISSUE THREAD

**Issue by danschultz** [google/test_runner.dart#10]
I have a browser test inside a sub-directory of my test folder, like so: `/test/models/model_test.dart`. When I run `run_tests`, the path for the import of that generated test in `__test_runner` is incorrect. Instead of being `import 'model_test.dart' as test;`, it's `import '/models/canvas_test.dart' as test;`

**Comment by nicolasgarnier** [comment]
Thanks Dan. Just fixed this as v0.2.7+1 and added 2 tests for it.

Thanks for reporting this!
