### ISSUE TITLE
Need to stop pub server after test_runner completed.

### ISSUE THREAD

**Issue by DisDis** [google/test_runner.dart#26]
Reproduce:
1) test_runner <...args...>
2) All browser test ok
3) test_runner <...args...>
4) exception "Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 7477"

$ps ax | grep dart
bin/dart --old_gen_heap_size=1024 /home/dis/bin/dart_dev/dart-sdk/bin/snapshots/pub.dart.snapshot serve test --port 7478

**Comment by ryanhanks-wf** [comment]
+1 I'm getting this as well. I'm on OS X.

**Comment by nicolasgarnier** [comment]
Sure I'll fix that soon! Sorry about this.

It's weird though because I'm on OSX as well and I've never noticed this issue... the pub serve process would always get killed automatically when the main process exits.

**Comment by nicolasgarnier** [comment]
Done. please update to the latest version! Let me know if you are facing other issues.

**Comment by nicolasgarnier** [comment]
Also guys I just pushed a new version where we will try to run `pub serve` on another port if the deafult port is already in use. We'll try another random port. You'll get this message:
```
Running all tests...
Warning: pub serve port 7478 already in use.
Trying to run pub serve with port 7669.
```
