### ISSUE TITLE
Tests randomly fail with `No top-level getter 'main' declared` error

### ISSUE THREAD

**Issue by danschultz** [google/test_runner.dart#28]
I have ~12 test suites, and one or two will randomly fail saying that it doesn't have a top-level `main` method, even though they do. It doesn't seem to happen if I set `--max-processes=1`.

This is reproducable in my the v0.2.1 branch in [stream_transformers](https://github.com/danschultz/stream_transformers). Checkout the branch and run `run_tests`.

**Comment by nicolasgarnier** [comment]
Can you please upgrade to the latest version? I pushed a fix for this earlier today.

**Comment by nicolasgarnier** [comment]
Let me know if you still encounter the issue.

**Comment by danschultz** [comment]
Seems to be working now, thanks!
