### ISSUE TITLE
The result output should contain information about skipped groups and tests

### ISSUE THREAD

**Issue by zoechi** [google/test_runner.dart#29]
The output shows information about found tests and succeeded, failed and errored tests but nothing about skipped groups, skipped tests and tests and groups within skipped groups.

**Comment by nicolasgarnier** [comment]
Could you tell me what you mean by skipped test/groups (just to make sure :D) do you mean when youa re using `skip_test()` or `skip_group()`?

**Comment by zoechi** [comment]
Yup, `skip_test()`, `skip_group()`

**Comment by Fox32** [comment]
I think the problem lies in the unittest package, till now it ```skip_test/skip_group``` is a no-op. There is no way to get these information, first we need support for that in unittest.

https://github.com/dart-lang/unittest/blob/stable/lib/unittest.dart#L117

**Comment by nicolasgarnier** [comment]
As @Fox32 mentions the test runner only runs the unittest. If the skipped tests information is not displayed by the unittest framework there is not much we can do from the test runner. You should file this as a feature request against the unittest package: https://github.com/dart-lang/unittest
