### ISSUE TITLE
The tests should be run in production mode (unchecked)

### ISSUE THREAD

**Issue by zoechi** [google/test_runner.dart#30]
It seems the tests are run in unchecked mode. 
There should be at least an option (command line argument) to run them in checked mode.

**Comment by nicolasgarnier** [comment]
Sounds good. I'll probably add a way to pass arbitrary flags to the underlying VMs that are spawned (this way you could even pass other flags like `--enable-async`

**Comment by zoechi** [comment]
Great!

**Comment by rayk** [comment]
+ 1 on the flags
