### ISSUE TITLE
test files that import package:observe are mistakingly classified as browser tests

### ISSUE THREAD

**Issue by Andersmholmgren** [google/test_runner.dart#8]
package observe is not browser dependent. I can run them fine in the ide and on command line vm.

**Comment by nicolasgarnier** [comment]
Strange...
Currently we rely on a trick to detect if a Dart file needs to be ran on the Browser or can be ran on standalone VM: We use dart2js with certain parameter which throws an error when the code needs browser... (I didn't come up with this trick so I;m not sure what's involved at this point)

@pq has plans to work on a replacement of this using the analyzer. (needs to add this funtionality in the analyzer basically).

@Andersmholmgren Could you share/point to a sample/Github repo test folder that would help me reproduce this? So I could investigate this deeper?

Cheers!

**Comment by Andersmholmgren** [comment]
Cool. Fixed now
