### ISSUE TITLE
Too many files opened at once

### ISSUE THREAD

**Issue by nicolasgarnier** [google/test_runner.dart#9]
Currently there is a limit of 256 files opened at once on mac OS X and on large projects running the browser test detection for all files in parallel is likely to trigger this limit.

We need to implement a limit on the max number of threads running concurrently (same for tests btw).

**Comment by seaneagan** [comment]
You may want to use this:

http://pub.dartlang.org/packages/pool

**Comment by nicolasgarnier** [comment]
Thanks for the pointer! That was indeed very convenient to use. Just added these pool (size 4 by default) as version 0.2.9
